CREATE TABLE duty_line (
  id        NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
  label_zh  VARCHAR2(255) NOT NULL,
  label_en  VARCHAR2(255) NOT NULL,
  phone     VARCHAR2(64)  NOT NULL,
  sort_order NUMBER       DEFAULT 100 NOT NULL,
  active    NUMBER(1)     DEFAULT 1 NOT NULL,
  CONSTRAINT pk_duty_line PRIMARY KEY (id)
);
ALTER TABLE security_setting ADD (duty_lines_enabled NUMBER(1) DEFAULT 1 NOT NULL);
