CREATE TABLE quick_link (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
  label_zh   VARCHAR2(255)  NOT NULL,
  label_en   VARCHAR2(255)  NOT NULL,
  url        VARCHAR2(1024) NOT NULL,
  icon       VARCHAR2(64),
  sort_order NUMBER         DEFAULT 100 NOT NULL,
  active     NUMBER(1)      DEFAULT 1 NOT NULL,
  CONSTRAINT pk_quick_link PRIMARY KEY (id)
);

INSERT INTO quick_link (label_zh, label_en, url, icon, sort_order, active)
VALUES ('IT 服务台', 'IT Service Desk', 'https://example.com/helpdesk', 'life-buoy', 10, 1);
