CREATE TABLE permission_group (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
  code       VARCHAR2(64)  NOT NULL,
  name_zh    VARCHAR2(255) NOT NULL,
  name_en    VARCHAR2(255) NOT NULL,
  active     NUMBER(1)     DEFAULT 1 NOT NULL,
  created_at TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_perm_group PRIMARY KEY (id),
  CONSTRAINT uk_perm_group_code UNIQUE (code)
);

CREATE TABLE permission_group_member (
  group_id    NUMBER       NOT NULL,
  employee_id VARCHAR2(64) NOT NULL,
  CONSTRAINT pk_pg_member PRIMARY KEY (group_id, employee_id),
  CONSTRAINT fk_pg_member_group FOREIGN KEY (group_id)
      REFERENCES permission_group(id) ON DELETE CASCADE
);
