CREATE TABLE uploaded_icon (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
  content_type VARCHAR2(64)  NOT NULL,
  file_size    NUMBER        NOT NULL,
  bytes        BLOB          NOT NULL,
  created_at   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_uploaded_icon PRIMARY KEY (id)
);
