CREATE TABLE announcement_type (
  id        NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
  code      VARCHAR2(64)  NOT NULL,
  label_zh  VARCHAR2(255) NOT NULL,
  label_en  VARCHAR2(255) NOT NULL,
  color     VARCHAR2(16)  DEFAULT 'blue' NOT NULL,
  icon      VARCHAR2(64)  DEFAULT 'info' NOT NULL,
  sort_order NUMBER       DEFAULT 100 NOT NULL,
  active    NUMBER(1)     DEFAULT 1 NOT NULL,
  CONSTRAINT pk_ann_type PRIMARY KEY (id),
  CONSTRAINT uk_ann_type_code UNIQUE (code)
);

CREATE TABLE announcement (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
  title_zh   VARCHAR2(255) NOT NULL,
  title_en   VARCHAR2(255) NOT NULL,
  body_zh    CLOB          NOT NULL,
  body_en    CLOB          NOT NULL,
  type_code  VARCHAR2(64)  NOT NULL,
  pinned     NUMBER(1)     DEFAULT 0 NOT NULL,
  starts_at  TIMESTAMP     NULL,
  ends_at    TIMESTAMP     NULL,
  active     NUMBER(1)     DEFAULT 1 NOT NULL,
  created_at TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_announcement PRIMARY KEY (id)
);

ALTER TABLE security_setting ADD (announcements_enabled NUMBER(1) DEFAULT 1 NOT NULL);

INSERT INTO announcement_type (code,label_zh,label_en,color,icon,sort_order) VALUES ('INFO','通知','Info','blue','info',10);
INSERT INTO announcement_type (code,label_zh,label_en,color,icon,sort_order) VALUES ('MAINTENANCE','维护','Maintenance','amber','wrench',20);
INSERT INTO announcement_type (code,label_zh,label_en,color,icon,sort_order) VALUES ('OUTAGE','停机','Outage','red','triangle-alert',30);
