CREATE TABLE enum_value (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
  category    VARCHAR2(32)  NOT NULL,
  code        VARCHAR2(64)  NOT NULL,
  label_zh    VARCHAR2(255) NOT NULL,
  label_en    VARCHAR2(255) NOT NULL,
  sort_order  NUMBER(10)    DEFAULT 0 NOT NULL,
  active      NUMBER(1)     DEFAULT 1 NOT NULL,
  created_at  TIMESTAMP     NOT NULL,
  updated_at  TIMESTAMP     NOT NULL,
  CONSTRAINT pk_enum_value PRIMARY KEY (id),
  CONSTRAINT uk_enum_category_code UNIQUE (category, code)
);

CREATE TABLE link (
  id             NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
  code           VARCHAR2(64)   NOT NULL,
  name_zh        VARCHAR2(255)  NOT NULL,
  name_en        VARCHAR2(255)  NOT NULL,
  url            VARCHAR2(1024) NOT NULL,
  icon           VARCHAR2(64)   NOT NULL,
  category_code  VARCHAR2(64)   NOT NULL,
  status_code    VARCHAR2(64)   NOT NULL,
  sort_order     NUMBER(10)     DEFAULT 0 NOT NULL,
  open_in_new_tab NUMBER(1)     DEFAULT 1 NOT NULL,
  created_at     TIMESTAMP      NOT NULL,
  updated_at     TIMESTAMP      NOT NULL,
  CONSTRAINT pk_link PRIMARY KEY (id),
  CONSTRAINT uk_link_code UNIQUE (code)
);

CREATE TABLE link_access_grant (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
  link_id     NUMBER       NOT NULL,
  grant_type  VARCHAR2(16) NOT NULL,
  grant_code  VARCHAR2(64) NOT NULL,
  CONSTRAINT pk_grant PRIMARY KEY (id),
  CONSTRAINT uk_grant UNIQUE (link_id, grant_type, grant_code),
  CONSTRAINT fk_grant_link FOREIGN KEY (link_id) REFERENCES link(id) ON DELETE CASCADE
);

CREATE TABLE label (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
  label_key   VARCHAR2(128)  NOT NULL,
  type        VARCHAR2(32)   NOT NULL,
  text_zh     VARCHAR2(1024) NOT NULL,
  text_en     VARCHAR2(1024) NOT NULL,
  created_at  TIMESTAMP      NOT NULL,
  updated_at  TIMESTAMP      NOT NULL,
  CONSTRAINT pk_label PRIMARY KEY (id),
  CONSTRAINT uk_label_key UNIQUE (label_key)
);

CREATE TABLE user_info (
  employee_id     VARCHAR2(64)  NOT NULL,
  display_name_zh VARCHAR2(255) NOT NULL,
  display_name_en VARCHAR2(255) NOT NULL,
  department_code VARCHAR2(64)  NOT NULL,
  role_code       VARCHAR2(64)  NOT NULL,
  email           VARCHAR2(255),
  active          NUMBER(1)     DEFAULT 1 NOT NULL,
  synced_at       TIMESTAMP     NOT NULL,
  CONSTRAINT pk_user_info PRIMARY KEY (employee_id)
);
