spring:
  application:
    name: cim-portal
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/cim_portal
    username: cim_portal
    password: cim_portal
  flyway:
    locations: classpath:db/migration/mariadb
app:
  security:
    mode: dev-jwt

---
spring:
  config:
    activate:
      on-profile: uat
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    locations: classpath:db/migration/oracle
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI}
app:
  security:
    mode: oidc

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    locations: classpath:db/migration/oracle
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI}
app:
  security:
    mode: oidc
